### ISSUE TITLE
[Presentation] ESLint

### ISSUE THREAD

**Issue by mpolichette** [UtahJS/meetups-slc-group#11]
What is it?  
What can it do?
How does it compare to JSHint, JSLint, and others

**Comment by kensnyder** [comment]
👍

**Comment by metasean** [comment]
@mpolichette - Thank you!  Great lightening talk!

**Comment by metasean** [comment]
@kensnyder  - Should this 'issue' be closed?

**Comment by waltercodes** [comment]
I think that's mostly up to @mpolichette. Do you feel like you covered things or would you like a larger time window to go into more about linting?

**Comment by mpolichette** [comment]
Sorry for slow response, yes lets close it.
