### ISSUE TITLE
Request: Hands-on tutorial and demo of GIT (and GitHub, or other UI)

### ISSUE THREAD

**Issue by CaptRat** [UtahJS/meetups-slc-group#13]

**Comment by kensnyder** [comment]
👍

**Comment by maddie927** [comment]
There was a really good Git intro at the 2015 (I think) Utah Geek Events conference up at the U.  I don't remember his name but I think I've seen him around at other meetups..

**Comment by JoniWeiss** [comment]
I'm actually preparing to present on this topic tomorrow at the JS Learners portion of the meetup. I'm planning for it to be hands-on, but I may assume that everyone who follows has it installed already, or allow about 5-10 minutes for installation (with help from knowledgeable volunteers?). I don't want to get caught up in the install process :-/

**Comment by kensnyder** [comment]
Thanks @JoniWeiss! Great job on your presentation!

I love the [gitignore](https://www.gitignore.io) tool you showed. Git interactive mode (`git add -i`) is pretty cool too! I hadn't seen that. 

Please add a comment on this issue with a link to your presentation and close this ticket 👍

**Comment by JoniWeiss** [comment]
Thank you, Ken! It needs some work, and I plan to add more content with more well-defined sections. I converted the PowerPoint slides to Google format. Here's the link to the Google doc:
https://docs.google.com/presentation/d/13z3tKqGsQDhkOZrRyhjrbM66cqfmfUJqHi-UysSxzOc/edit?usp=sharing
