### ISSUE TITLE
[PRESENTATION] Hapi-Swagger

### ISSUE THREAD

**Issue by cgood92** [UtahJS/meetups-slc-group#15]
Why you should never write your RESTFUL API in anything else.  

I would like to volunteer to present on this topic, if that would be interesting and acceptable.  I have used hapi-swagger in several different ways.  I cannot show production projects, but here is a sample sandbox project: https://github.com/cgood92/lunchinator 

Let me know if you would like me to present on this topic.

Other things I wouldn't mind presenting on:

- Regex
- ES6
- VIM 
- MarkLogic as a NoSQL option
- Firebase NoSQL

**Comment by kensnyder** [comment]
@cgood92 Clint, that sounds great. Can you present on hapi-swagger at the January 17th meetup?

**Comment by cgood92** [comment]
@kensnyder I would be happy to.  Thank you for the opportunity.  I hope that I can give a good presentation that will benefit people.  

I'll plan on doing a presentation for Hapi-Swagger on January 17th.  While presenting on that topic, there will be opportunity to also explain: Hapi, Joi, Boom, API benefits/practices, Basic Authentication, and a small plugin for NoSQL and Firebase, since that will all be encompassed in the API example I want to demo/code.  I'll get an example repo going, and people can download and follow along.

Thanks!  Let me know if anything changes.

**Comment by cgood92** [comment]
@kensnyder 

Just wanted to confirm with you that I will still do the meetup presentation on January 17th.  I will be presenting on several tips and packages to make an awesome API very quickly.  

Is there any chance that we can update the event here https://www.meetup.com/UtahJS/events/236384673/, with a brief description, and more importantly a link to the git repo I would like to present on?  If so, that would be great.  If not, that is fine.  

2 questions: is the time limit an hour, like it says on Meetup.com, or is it 25 minutes, like I've noticed all the recorded videos have been?  Also, speaking of recorded videos - do you record all of them?  I would like to record, so if you've got that covered that's awesome.  If not, then I will figure out how to do it myself.

But, it would be awesome if we could add this:

# Swagger
_a way to find Hapi-Nes and Joi_

Presenter: [Clint Goodman](https://github.com/cgood92)

Come learn how to quickly develop a comprehensive API using hapi-swagger.  We will be discussing Hapi, Swagger, Firebase, Nes, Joi, Boom, hapi-auth-basic, and other technologies.  

Follow along the presentation with this accompanying project: https://github.com/cgood92/hapi-swagger-training/tree/utahjs.

**Comment by kensnyder** [comment]
@cgood92 Thanks! I updated the meetup description. See you then!
