### ISSUE TITLE
[PRESENTATION] Use Maybe's and Either's for worry-free dot-chaining

### ISSUE THREAD

**Issue by whiteinge** [UtahJS/meetups-slc-group#16]
A practical introduction (and demonstration) for using the `Maybe` and `Either` patterns to perform a complex series of operations without having to stop and check for null/undefined/errors at each step along the way.

This presentation will focus on solving real-world use-cases and won't mention the 'M' word.

**Comment by kensnyder** [comment]
By 'M' word do you mean monad? Those do seem esoteric and confusing.

**Comment by whiteinge** [comment]
Yeah. 😀  You can get a lot of benefit by using them without even knowing you're using them (jQuery (sort of) and RxJS are decent examples) because they can provide an awesome interface. IMO, it's a common mistake that people try to explain how to build them or how to ensure they follow all the "laws" before they even explain why the audience should care. This one will be entirely end-user focused, not implementer focused.

**Comment by whiteinge** [comment]
I see the April 18 SLC meet is looking for a presenter. If there's interest, I can present then.

**Comment by kensnyder** [comment]
That would be great. Do you want the title to be `Use Maybe's and Either's for worry-free dot-chaining`? How long would you like to present? 20 min, 40 min or 60 min?

**Comment by whiteinge** [comment]
Cool. Yes to the title. I have enough content to fill the hour. Let me know if you'd like to line something else up during that time and I can cut it back to 40.

**Comment by kensnyder** [comment]
Great! Meetup is now [updated](https://www.meetup.com/UtahJS/events/238875893/).
