### ISSUE TITLE
[PRESENTATION] I'd like to present on How to build your own WebExtension add-on for Firefox.

### ISSUE THREAD

**Issue by thehashrocket** [UtahJS/meetups-slc-group#17]
Firefox is an open-source web browser that cares about user control and privacy, and add-ons provide a safe, simple, and powerful way to personalize your browsing experience. From blocking ads to organizing tabs, add-ons help make Firefox your own.

It’s very easy to create add-ons for Firefox with WebExtensions. This Web-based technology framework offers a powerful way to create browser extensions that can be easily ported to Chrome, Opera, and Edge, and you only need to know HTML, JavaScript and CSS to build them.

Through this activity you’ll learn how easy it is to create add-ons to solve real problems and make users lives and the web better.

**Comment by maddie927** [comment]
Would you like to present at the next UtahJS Orem meetup?

**Comment by thehashrocket** [comment]
when would that be?

**Comment by maddie927** [comment]
July 6th
https://www.meetup.com/UtahJS/events/239741031/

**Comment by thehashrocket** [comment]
That would be great! I'll be there.

**Comment by maddie927** [comment]
I've updated the meetup info.
